### ISSUE TITLE
BUG : Impossible de démarrer le jeu avec mc forge 1.12.2 

### ISSUE THREAD

**Issue by FireBlaim** [FlowArg/FlowUpdater#11]
Bonjour/Bonsoir,

Quand je démarre le téléchargement des fichiers du jeu, tout semble fonctionner (les assets, libs, natives et le client.jar sont bien mis) mais lorsque l'installation de forge se déroule, non seulement je trouve qu'elle est très rapide mais le jeu ne semble pas être patché et du coup il ne démarre pas car il ne trouve pas la classe net.minecraft.launchwrapper.Launch qui vient de forge.

Voici le code de l'updater : 

![image](https://user-images.githubusercontent.com/29017418/178123229-da1418fd-5c8e-4836-aecb-49f7e05fb02e.png)

et voici les logs de l'installateur de forge présent dans le dossier de destination (je précise qu'avec cette même version prise sur internet c'est-à-dire sur le site de mc forge et bien ça fonctionne nickel) :

![image](https://user-images.githubusercontent.com/29017418/178123281-794ee0d7-4076-4299-8ecc-2003537a35b2.png)

PS : j'ai essayé de mettre dans le build.gradle la lib jdom pour voir si ça allait changer quelque chose mais nope

PS 2 : Je suis sur ArchLinux avec le Java 8 de Oracle

**Comment by FlowArg** [comment]
Il faut utiliser ForgeVersionType.NEW comme l'indique la doc. De plus, je te conseille dans la version de Forge d'ajouter 1.12.2- avant la version de forge pour éviter des soucis (au cas ou)

**Comment by FireBlaim** [comment]
> Il faut utiliser ForgeVersionType.NEW comme l'indique la doc. De plus, je te conseille dans la version de Forge d'ajouter 1.12.2- avant la version de forge pour éviter des soucis (au cas ou)

Effectivement, j'avais mal compris la doc. Déso du dérangement !
