### ISSUE TITLE
Curse Forge Token

### ISSUE THREAD

**Issue by jacobtread** [FlowArg/FlowUpdater#12]
Hey are you sure its a good idea for you to upload your curse forge api token to a public repository.... thats really not something you should be doing with any sort of api tokens and just asking people nicely to change it when forking is something that i don't think will work out for you it might be better for you to just have it in some sort of configuration along with a guide for users to help them create a token?

**Comment by wowkster** [comment]
I agree, you should never expose API tokens in a public repository for really any reason

**Comment by FlowArg** [comment]
I totally agree with you in the fact that distributing a "private" API Key isn't good. However, I don't have so much choices...

To understand my point, you need to know these two points:
- The API Key isn't given to anyone. You can read the [CurseForge Article about the 3rd Party API](https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key#key)...
- Before making the commit, I've asked on the [CurseForge Dev Discord server](https://discord.gg/257dCwUNvu) and an admin told me this: ![Screenshot_20220716-093425_Discord.png](https://user-images.githubusercontent.com/52298108/179345245-75c1926a-9fe9-4e0a-b6c1-f0498b98977c.png).
So I simply followed his instructions. If you have better ideas, I'll gladly take them!! Make sure that it is allowed by the [Terms of Service](https://support.curseforge.com/en/support/solutions/articles/9000207405-curse-forge-3rd-party-api-terms-and-conditions) of course!

**Comment by jacobtread** [comment]
I understand where you're coming from with this however rather than giving out complete control to this key that as you've stated has to be applied for instead you could create an api or service of such which abstracts the api aswell as your token away and with said api you could have dedicated routes for only the specific things that your code needs to do

**Comment by FlowArg** [comment]
It's an idea but how to deploy it?
I see atm one possibility :
I need to find a server (and pay for it) to host an API. But the thing is everyone depend of this service. If the server shuts down for any reason, all the applications using FU will be down...

I hope there is more possibilities...

**Comment by jacobtread** [comment]
Yeah that could be an issue im not too sure what to do about that you might be out of other options in that regard ill be closing this issue now that I've shared as much as I can
