### ISSUE TITLE
BUG : Impossible de mettre à jour le jeu avec mon Launcher

### ISSUE THREAD

**Issue by Nozyx59** [FlowArg/FlowUpdater#18]
Bonjour / Bonsoir, 
Lors de la mise-à-jour du jeu j'ai une erreur...

Logs concernés : 
```
[05:45:10] [NywenLauncher] [INFO]: Lancement du launcher.
[05:45:12] [NywenLauncher] [INFO]: Rafraichissement du compte Microsoft.
[05:45:19] [NywenLauncher] [INFO]: Downloading NywenClient.json from https://nywenmc.github.io/assets/nywenclient/NywenClient.json...
[05:45:20] [NywenLauncher] [INFO]: ------------------------- FlowUpdater for Minecraft NywenClient v1.8.1 -------------------------
[05:45:20] [NywenLauncher] [INFO]: Mise-�-jour du jeu
[05:45:20] [NywenLauncher] [INFO]: Reading data about NywenClient Minecraft version...
[OpenLauncherLib] Exception attrapee !
# NywenMC Crash Report
#
# At : 2023/09/13 17:45:20
#
# Exception : NullPointerException

# java.lang.NullPointerException
#     fr.flowarg.flowupdater.download.VanillaReader.parseClient(VanillaReader.java:139)
#     fr.flowarg.flowupdater.download.VanillaReader.read(VanillaReader.java:67)
#     fr.flowarg.flowupdater.FlowUpdater.loadVanillaStuff(FlowUpdater.java:159)
#     fr.flowarg.flowupdater.FlowUpdater.updateMinecraft(FlowUpdater.java:139)
#     fr.flowarg.flowupdater.FlowUpdater.update(FlowUpdater.java:126)
#     fr.nywenmc.nywenlauncher.NywenLauncher.lambda$update$1(NywenLauncher.java:146)
#     java.lang.Thread.run(Thread.java:750)
[OpenLauncherLib] Ecriture du crash report dans C:\Users\***\AppData\Roaming\.nywenmc\launcher-crashes\crash-0.txt
```

(NywenLauncher est le launcher de mon serveur minecraft)

Voici le code de ma méthode de mise-à-jour :

```
public static void update() {
  if (authInfos == null) return;

  Frame.getInstance().getPanel().setProgressBarText("Mise-à-jour du jeu");
  Frame.getInstance().getPanel().getProgressBar().setValue(100);
  Frame.getInstance().getPanel().getPlayBtn().setEnabled(false);
  Frame.getInstance().getPanel().getDisconnectBtn().setEnabled(false);

  Thread t = new Thread(() -> {
    try {
      MCP mcp = MCP.getMCPFromJson("https://nywenmc.github.io/assets/nywenlauncher/MCP-Version.json");
      JsonObject versionJSON = IOUtils.readJson(new URL("https://nywenmc.github.io/assets/nywenclient/NywenClient.json")).getAsJsonObject();
      IOUtils.download(logger, new URL("https://nywenmc.github.io/assets/nywenclient/NywenClient.json"), gameDir.resolve("NywenClient.json"));
      VanillaVersion version = new VanillaVersion.VanillaVersionBuilder().withCustomVersionJson(versionJSON).withName("NywenClient").withMCP(mcp).build();

      IProgressCallback callback = new IProgressCallback() {
        public void init(ILogger logger) {
          logger.info("Mise-à-jour du jeu");
        }

        public void step(Step step) {
          Frame.getInstance().getPanel().setProgressBarText((UpdaterMessages.valueOf(step.name())).msg);
        }

        public void onFileDownloaded(Path path) {
          Frame.getInstance().getPanel().setProgressBarText(path.getFileName().toString());
        }

        public void update(DownloadList.DownloadInfo info) {
          int progress = (int)(info.getDownloadedBytes() * 100 L / info.getTotalToDownloadBytes());
          NywenLauncher.logger.info("Mise-à-jour : " + progress + "%");
          Frame.getInstance().getPanel().getProgressBar().setValue(progress);
        }
      };

      FlowUpdater updater = new FlowUpdater.FlowUpdaterBuilder().withLogger(logger).withProgressCallback(callback).withVanillaVersion(version).build();
      updater.update(gameDir);
    } catch (Exception e) {
      Frame.getInstance().getPanel().getProgressBar().setForeground(Color.RED);
      Frame.getInstance().getPanel().getProgressBar().setBorderPainted(false);
      Frame.getInstance().getPanel().setProgressBarText("Impossible de mettre-à-jour le jeu");
      Frame.getInstance().getPanel().getProgressBar().setValue(100);
      getCrashReporter().catchError(e, "Echec de la mise-du jeu.");
    }

    try {
      launch();
    } catch (Exception e) {
      Frame.getInstance().getPanel().getProgressBar().setForeground(Color.RED);
      Frame.getInstance().getPanel().getProgressBar().setBorderPainted(false);
      Frame.getInstance().getPanel().setProgressBarText("Impossible de lancer le jeu");
      Frame.getInstance().getPanel().getProgressBar().setValue(100);
      getCrashReporter().catchError(e, "Echec du lancement du jeu.");
    }
  });

  t.start();
}
```

Merci !

**Comment by Nozyx59** [comment]
> N utilise pas .withMCP et withVersionJson en même temps. Soit l un soit l autre. + vérifie que les liens fonctionnent. J ai testé le withJsonVersion et ca n a pas trouvé le contenu.

Je vais essayer pour voir, en tout cas merci
Je vais voir très vite

**Comment by Nozyx59** [comment]
> N utilise pas .withMCP et withVersionJson en même temps. Soit l un soit l autre. + vérifie que les liens fonctionnent. J ai testé le withJsonVersion et ca n a pas trouvé le contenu.

Pour le .withCustomVersionJson moi je le trouve à https://nywenmc.github.io/assets/nywenclient/NywenClient.json c'est bizarre

**Comment by FlowArg** [comment]
par contre, dans ton .json, il manque dans "downloads": {} les infos nécéssaires pour télécharger le jeu correctement comme le json de base de minecraft. C'est impératif pour que le téléchargement se fasse sans soucis comme tu as.

**Comment by Nozyx59** [comment]
> par contre, dans ton .json, il manque dans "downloads": {} les infos nécéssaires pour télécharger le jeu correctement comme le json de base de minecraft. C'est impératif pour que le téléchargement se fasse sans soucis comme tu as.

je pense que je vais juste l'enlever vu que le json sert un peut à rien pour moi donc voilà

**Comment by Nozyx59** [comment]
Après avoir enlevé le json custom j'ai encore une erreur : 

```
[06:17:40] [FlowUpdater] [ERROR]: An error occurred : java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:274)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read(BufferedReader.java:182)
	at fr.flowarg.flowupdater.utils.IOUtils.readJson(IOUtils.java:158)
	at fr.flowarg.flowupdater.versions.VanillaVersion.<init>(VanillaVersion.java:59)
	at fr.flowarg.flowupdater.versions.VanillaVersion.<init>(VanillaVersion.java:26)
	at fr.flowarg.flowupdater.versions.VanillaVersion$VanillaVersionBuilder.build(VanillaVersion.java:352)
	at fr.nywenmc.nywenlauncher.NywenLauncher.lambda$update$1(NywenLauncher.java:122)
	at java.lang.Thread.run(Thread.java:750)
# NywenMC Crash Report
#
# At : 2023/09/13 18:17:40
#
# Exception : IllegalStateException

# java.lang.IllegalStateException: Not a JSON Object: null
#     com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
#     fr.flowarg.flowupdater.utils.IOUtils.readJson(IOUtils.java:170)
#     fr.flowarg.flowupdater.versions.VanillaVersion.<init>(VanillaVersion.java:59)
#     fr.flowarg.flowupdater.versions.VanillaVersion.<init>(VanillaVersion.java:26)
#     fr.flowarg.flowupdater.versions.VanillaVersion$VanillaVersionBuilder.build(VanillaVersion.java:352)
#     fr.nywenmc.nywenlauncher.NywenLauncher.lambda$update$1(NywenLauncher.java:122)
#     java.lang.Thread.run(Thread.java:750)
[OpenLauncherLib] Ecriture du crash report dans C:\Users\eziot\AppData\Roaming\.nywenmc\launcher-crashes\crash-0.txt
[OpenLauncherLib] Exception attrapee !
```

**Comment by FlowArg** [comment]
sûrement le .withName que tu dois mettre dans ta version concernée

**Comment by Nozyx59** [comment]
> sûrement le .withName que tu dois mettre dans ta version concernée

VanillaVersion version = new VanillaVersion.VanillaVersionBuilder().withCustomVersionJson(versionJSON).withName(**"NywenClient"**).withMCP(mcp).build();

**Comment by FlowArg** [comment]
oui justement faut mettre genre 1.16.5

**Comment by Nozyx59** [comment]
> oui justement faut mettre genre 1.16.5

D'accord je vais essayer

**Comment by Nozyx59** [comment]
> oui justement faut mettre genre 1.16.5

Parfait le jeu s'est lancé correctement mais je n'ai pas les sons qui sont pris en compte dans le jeu `[14:25:59] [main/WARN]: Missing sound for event: minecraft:entity.wither.ambient` alors que les assets ont bien été téléchargés

**Comment by Nozyx59** [comment]
> > oui justement faut mettre genre 1.16.5
> 
> Parfait le jeu s'est lancé correctement mais je n'ai pas les sons qui sont pris en compte dans le jeu `[14:25:59] [main/WARN]: Missing sound for event: minecraft:entity.wither.ambient` alors que les assets ont bien été téléchargés

C'est un problème que j'avais déjà avant mais je n'ai jamais compris pourquoi ça ne fonctionnait pas

**Comment by cakihorse** [comment]
> > > oui justement faut mettre genre 1.16.5
> > 
> > 
> > Parfait le jeu s'est lancé correctement mais je n'ai pas les sons qui sont pris en compte dans le jeu `[14:25:59] [main/WARN]: Missing sound for event: minecraft:entity.wither.ambient` alors que les assets ont bien été téléchargés
> 
> C'est un problème que j'avais déjà avant mais je n'ai jamais compris pourquoi ça ne fonctionnait pas

Hey ! Tu lances le jeu avec mcp ? Si oui, ça vient de ton jar (mcp) normalement.

**Comment by Nozyx59** [comment]
> > > > oui justement faut mettre genre 1.16.5
> > > 
> > > 
> > > Parfait le jeu s'est lancé correctement mais je n'ai pas les sons qui sont pris en compte dans le jeu `[14:25:59] [main/WARN]: Missing sound for event: minecraft:entity.wither.ambient` alors que les assets ont bien été téléchargés
> > 
> > 
> > C'est un problème que j'avais déjà avant mais je n'ai jamais compris pourquoi ça ne fonctionnait pas
> 
> Hey ! Tu lances le jeu avec mcp ? Si oui, ça vient de ton jar (mcp) normalement.

Comment ça ? J'ai toujours eu ce problème mais pourtant avec le Launcher officiel ça marche donc je pense que ça vien de ma méthode launch() ça doit pas bien prendre en compte les assets audio

**Comment by FlowArg** [comment]
Viens Discord par contre, maintenant qu'on sait que ce n'est plus un pb de flowupdater.
