### ISSUE TITLE
BUG : Cannot use the Updater

### ISSUE THREAD

**Issue by skitou** [FlowArg/FlowUpdater#2]
**Describe the bug**
Cannot use the Updater

**To Reproduce**
Try to use the updater

**Screenshots**
![image](https://user-images.githubusercontent.com/38993289/91663163-71741780-eae7-11ea-9082-9f0899570bcf.png)
![image](https://user-images.githubusercontent.com/38993289/91663288-345c5500-eae8-11ea-8a0e-ffd02557d8e2.png)

**Desktop (please complete the following information):**
**Operating System: Manjaro Linux**
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
**Kernel Version: 5.7.17-2-MANJARO**
OS Type: 64-bit

**Comment by FlowArg** [comment]
Hello,
If you are using the latest version of FlowUpdater (1.1.11), you must specify updater options (withUpdaterOptions on the builder).
