### ISSUE TITLE
BUG : No Sound, Background and Icon

### ISSUE THREAD

**Issue by xii69** [FlowArg/FlowUpdater#20]
**Describe the bug**
No Sound, Background and Game icon

**To Reproduce**
1. Launching minecraft using this code:
```java
private static void launch(String username, int memory, boolean update) throws Exception {
    if (update) {
        VanillaVersion version = new VanillaVersion.VanillaVersionBuilder()
            .withName("1.19.4")
            .build();
        FabricVersion builder = new FabricVersion.FabricVersionBuilder()
            .withFabricVersion("0.14.22")
            .withModrinthModPack(new ModrinthModPackInfo("WTNMThBB", true))
            .build();
        FlowUpdater updater = new FlowUpdater.FlowUpdaterBuilder()
            .withVanillaVersion(version)
            .withModLoaderVersion(builder)
            .build();
        updater.update(GameDirGenerator.createGameDir("neverland", true));
    }

    GameInfos infos = new GameInfos("neverland", new GameVersion("1.19.4", GameType.FABRIC), new GameTweak[]{});
    AuthInfos authInfos = new AuthInfos(username, "token", "uuid");
    ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(infos, GameFolder.FLOW_UPDATER_1_19_SUP, authInfos);
    profile.getVmArgs().add(0, "-Xmx" + memory + "M");
    profile.getVmArgs().add(0, "-Xms" + memory + "M");
    ExternalLauncher launcher = new ExternalLauncher(profile);
    Process game = launcher.launch();
}
```

**Expected behavior**
The launched client should have sound and background image in the main menu

**Comment by antoineok** [comment]
Je dirait plutot que ca viens de l'Open Launcher Lib

**Comment by antoineok** [comment]
Tu as quelle version de l'open launcher lib?

**Comment by antoineok** [comment]
et surtout, je te conseil de ne pas mettre la mise a jour dans une condition. Le jeu ne sera pas retéléchargé, mais il y aura quand meme une vérification des fichiers de mc

**Comment by xii69** [comment]
> Tu as quelle version de l'open launcher lib? Celle de Litarvan, ou celle de Flow?

Flow

**Comment by xii69** [comment]
> et surtout, je te conseil de ne pas mettre la mise a jour dans une condition. Le jeu ne sera pas retéléchargé, mais il y aura quand meme une vérification des fichiers de mc

Its a long story, I'll share a .zip file of this launcher for those people who want to use it which all assets are downloaded already

**Comment by antoineok** [comment]
> > Tu as quelle version de l'open launcher lib? Celle de Litarvan, ou celle de Flow?
> 
> Flow

Then, for the MC version you are using, i recommand you to use NoFramework instead.

**Comment by antoineok** [comment]
> > et surtout, je te conseil de ne pas mettre la mise a jour dans une condition. Le jeu ne sera pas retéléchargé, mais il y aura quand meme une vérification des fichiers de mc
> 
> Its a long story, I'll share a .zip file of this launcher for those people who want to use it which all assets are downloaded already

Even if you share a zip, the valid files won't be re downloaded, unless the checksum or the size isn't the same as the one Mojang list in the download manifest

**Comment by xii69** [comment]
Still didn't understood how I can fix the missing sound and other stuff.

**Comment by FlowArg** [comment]
Instead of using the old GameInfos stuff etc, you can use the `NoFramework` class. It's easier and avoid a lot of problems to launch the game.
`NoFramework noFramework = new NoFramework(GameDirGenerator.createGameDir("neverland", true), authInfos, GameFolder.FLOW_UPDATER_1_19_SUP);`
to add your ram arguments, you can use `noFramework.getAdditionalVmArgs().add`
and then
`Process process = noFramework.launch();`

**Comment by FlowArg** [comment]
maybe! a clean env is always better to test these kind of things lmao

**Comment by xii69** [comment]
Yea for sure, one more question and the last one, I want to bundle a JRE 17 with this launcher, how can I set this launcher to use a custom java path?

**Comment by xii69** [comment]
Thanks.
